spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Warehouse?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      format_sql: true
      globally_quoted_identifiers=true:defer-datasource-initialization: true


#  mvc: format.date-time=yyyy-MM-dd HH:mm

#  jackson:
#   date-format: yyyy-MM-dd　HH:mm
#   serialization:
#    write-dates-as-timestamps: false


# sql:
#    init:
#      mode: always